export default [
  {
    planName: "Personal Plan",
    for: "For You",
    type: "Individual",
    price: "Starting at ₹850 per month",
    billing: "Billed monthly or annually. Cancel anytime.",
    btn: "Start subscription",
    features: [
      "Access to 11,000+ top courses",
      "Certification prep",
      "Goal-focused recommendations",
      "AI-powered coding exercises",
    ],
  },
  {
    planName: "Team Plan",
    for: "For Your team",
    type: "2 to 20 people",
    price: "₹1,167 a month per user",
    billing: "Billed annually. Cancel anytime.",
    btn: "Start subscription",
    features: [
      "Access to 11,000+ top courses",
      "Certification prep",
      "Goal-focused recommendations",
      "AI-powered coding exercises",
      "Analytics and adoption reports",
    ],
  },
  {
    planName: "Enterprise Plan",
    for: "For Your whole organization",
    type: "More than 20 people",
    price: "Contact sales for pricing",
    btn: "Request a demo",
    features: [
      "Access to 25,000+ top courses",
      "Certification prep",
      "Goal-focused recommendations",
      "AI-powered coding exercises",
      "Advanced analytics and insights",
      "Dedicated customer success team",
      "International course collection featuring 15 languages",
      "Customizable content",
      "Hands-on tech training with add-on",
      "Strategic implementation services with add-on",
    ],
  },
];
